### ISSUE TITLE
InitializeDefaultConfiguration fails with missing assembly

### ISSUE THREAD

**Issue by w1op** [ranorex/Ranorex-Jira-Integration#8]
Downloading the latest Ranorex.Jira integration package from within Ranorex (v0.1.2) and trying to execute the initialization step the following error message appears.

Die Datei oder Assembly "RestSharp, Version=106.2.2.0, Culture=neutral, PublicKeyToken=598062e77f915f75" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden. (InnerException: -- ) 

The additional packages being automatically downloaded are
  <package id="Atlassian.SDK" version="10.4.0" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net452" />
  <package id="Ranorex.Jira" version="0.1.2" targetFramework="net452" />
  <package id="RestSharp" version="106.5.4" targetFramework="net452" />

**Comment by ahoisl** [comment]
@w1op The correct version of RestSharp required by the Jira integration dependencies is "106.5.4.0". Could it be that you hard-coded the reference? Try removing the Nuget Packages "RestSharp" and "Ranroex Jira reporting modules" and then install the "Ranorex Jira" integation again. This should readd the correct references.

**Comment by w1op** [comment]
@ahoisl I created a blank project and just added the Ranorex.Jira package. All related and required packages were loaded successfully without updating them to their latest versions.

I tried this on two different environments with, of course, two different results :(
- Windows 10 Enterprise: Error as reported
- Windows 8.1 Enterprise: Everything works fine

P.S.: You are right I fiddled a bit around with the dependencies and versions but after your suggestion I started from scratch and got the same error.

**Comment by ahoisl** [comment]
Hmm, I can just guess at this point since I just tried again on Windows 10 and everything worked out right. The RestSharp version must be "106.5.4.0" as you can see on the NuGet package for dependencies:
https://www.nuget.org/packages/Ranorex.Jira/0.1.2

I can only imagine that a different RestSharp version is lying around on your system and is being used for compilation. Can you click on the RestSharp reference and inspect its properties?
Make sure the reference points to "..\packages\RestSharp.106.5.4\lib\net452\RestSharp.dll" using a relative path.

In the project file you can also make sure that the following reference is used:
```
    <Reference Include="RestSharp, Version=106.5.4.0, Culture=neutral, PublicKeyToken=598062e77f915f75">
      <HintPath>..\packages\RestSharp.106.5.4\lib\net452\RestSharp.dll</HintPath>
    </Reference>```

**Comment by w1op** [comment]
@ahoisl Thanks a lot for your further suggestions. After removing everything related to RestSharp and Nuget and reinstalling Ranorex it is running as expected now.
